export const images = [
  {
    src:"/images/makeup1.JPG",
    thumbnail: "/images/makeup1.JPG",
    thumbnailWidth: 150,
    thumbnailHeight: 174,
  },
  {
    src:"/images/makeup2.JPG",
    thumbnail: "/images/makeup2.JPG",
    thumbnailWidth: 150,
    thumbnailHeight: 174,
  },
  {
    src:"/images/makeup3.JPG",
    thumbnail: "/images/makeup3.JPG",
    thumbnailWidth: 150,
    thumbnailHeight: 174,
  },
  {
    src:"/images/makeup5.JPG",
    thumbnail: "/images/makeup5.JPG",
    thumbnailWidth: 150,
    thumbnailHeight: 174,
  },
  {
    src:"/images/hair2.JPG",
    thumbnail: "/images/hair2.JPG",
    thumbnailWidth: 150,
    thumbnailHeight: 174,
  },
  {
    src:"/images/makeup6.JPG",
    thumbnail: "/images/makeup6.JPG",
    thumbnailWidth: 150,
    thumbnailHeight: 174,
  },
  {
    src:"/images/makeup7.JPG",
    thumbnail: "/images/makeup7.JPG",
    thumbnailWidth: 250,
    thumbnailHeight: 174,
  },
  {
    src:"/images/makeup8.JPG",
    thumbnail: "/images/makeup8.JPG",
    thumbnailWidth: 150,
    thumbnailHeight: 174,
  },
  {
    src:"/images/makeup9.JPG",
    thumbnail: "/images/makeup9.JPG",
    thumbnailWidth: 150,
    thumbnailHeight: 174,
  },
  {
    src:"/images/makeup10.JPG",
    thumbnail: "/images/makeup10.JPG",
    thumbnailWidth: 150,
    thumbnailHeight: 174,
  },
  {
    src:"/images/makeupBA2.JPEG",
    thumbnail: "/images/makeupBA2.JPEG",
    thumbnailWidth: 300,
    thumbnailHeight: 174,
  },
  {
    src:"/images/hair1.JPG",
    thumbnail: "/images/hair1.JPG",
    thumbnailWidth: 150,
    thumbnailHeight: 174,
  },
  {
    src:"/images/hair3.JPG",
    thumbnail: "/images/hair3.JPG",
    thumbnailWidth: 150,
    thumbnailHeight: 174,
  },
  {
    src:"/images/makeupBA1.JPEG",
    thumbnail: "/images/makeupBA1.JPEG",
    thumbnailWidth: 275,
    thumbnailHeight: 174,
  },
  {
    src:"/images/hair4.JPG",
    thumbnail: "/images/hair4.JPG",
    thumbnailWidth: 150,
    thumbnailHeight: 174,
  },
  {
    src:"/images/hair5.JPG",
    thumbnail: "/images/hair5.JPG",
    thumbnailWidth: 150,
    thumbnailHeight: 174,
  },
  {
    src:"/images/hair6.JPG",
    thumbnail: "/images/hair6.JPG",
    thumbnailWidth: 150,
    thumbnailHeight: 174,
  },
  {
    src:"/images/hair7.JPG",
    thumbnail: "/images/hair7.JPG",
    thumbnailWidth: 150,
    thumbnailHeight: 174,
  },
  {
    src:"/images/pose1.JPG",
    thumbnail: "/images/pose1.JPG",
    thumbnailWidth: 150,
    thumbnailHeight: 174,
  },
  {
    src:"/images/pose2.JPG",
    thumbnail: "/images/pose2.JPG",
    thumbnailWidth: 150,
    thumbnailHeight: 174,
  },
  {
    src:"/images/pose3.JPG",
    thumbnail: "/images/pose3.JPG",
    thumbnailWidth: 150,
    thumbnailHeight: 174,
  },

]