export const images = {
  null: [],
  makeup: [
    {
      src: "/images/makeup1.JPG",
      thumbnail: "/images/makeup1.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup2.JPG",
      thumbnail: "/images/makeup2.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup3.JPG",
      thumbnail: "/images/makeup3.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup4.JPG",
      thumbnail: "/images/makeup4.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup5.JPG",
      thumbnail: "/images/makeup5.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup6.JPG",
      thumbnail: "/images/makeup6.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup7.JPG",
      thumbnail: "/images/makeup7.JPG",
      thumbnailWidth: 230,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup8.JPG",
      thumbnail: "/images/makeup8.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup9.JPG",
      thumbnail: "/images/makeup9.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup10.JPG",
      thumbnail: "/images/makeup10.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup11.JPG",
      thumbnail: "/images/makeup11.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup12.JPG",
      thumbnail: "/images/makeup12.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup13.JPG",
      thumbnail: "/images/makeup13.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup14.JPG",
      thumbnail: "/images/makeup14.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup15.JPG",
      thumbnail: "/images/makeup15.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup16.JPG",
      thumbnail: "/images/makeup16.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup17.jpg",
      thumbnail: "/images/makeup17.jpg",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup18.JPG",
      thumbnail: "/images/makeup18.JPG",
      thumbnailWidth: 250,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup19.JPG",
      thumbnail: "/images/makeup19.JPG",
      thumbnailWidth: 250,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup20.jpg",
      thumbnail: "/images/makeup20.jpg",
      thumbnailWidth: 250,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup21.jpg",
      thumbnail: "/images/makeup21.jpg",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/hair1.JPG",
      thumbnail: "/images/hair1.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/hair2.JPG",
      thumbnail: "/images/hair2.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/hair3.JPG",
      thumbnail: "/images/hair3.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/hair4.JPG",
      thumbnail: "/images/hair4.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/hair5.JPG",
      thumbnail: "/images/hair5.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/hair6.JPG",
      thumbnail: "/images/hair6.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/hair7.JPG",
      thumbnail: "/images/hair7.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
  ],
  dress: [
    {
      src: "/images/dress2.JPG",
      thumbnail: "/images/dress2.JPG",
      thumbnailWidth: 130,
      thumbnailHeight: 174,
    },
    {
      src: "/images/dress3.JPG",
      thumbnail: "/images/dress3.JPG",
      thumbnailWidth: 250,
      thumbnailHeight: 174,
    },
    {
      src: "/images/dress4.JPG",
      thumbnail: "/images/dress4.JPG",
      thumbnailWidth: 250,
      thumbnailHeight: 174,
    },
    {
      src: "/images/dress5.JPG",
      thumbnail: "/images/dress5.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/dress6.JPG",
      thumbnail: "/images/dress6.JPG",
      thumbnailWidth: 220,
      thumbnailHeight: 174,
    },
    {
      src: "/images/dress7.JPG",
      thumbnail: "/images/dress7.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/dress8.JPG",
      thumbnail: "/images/dress8.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/dress9.JPG",
      thumbnail: "/images/dress9.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/dress10.JPG",
      thumbnail: "/images/dress10.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/dress11.JPG",
      thumbnail: "/images/dress11.JPG",
      thumbnailWidth: 250,
      thumbnailHeight: 174,
    },
    {
      src: "/images/dress12.jpg",
      thumbnail: "/images/dress12.jpg",
      thumbnailWidth: 170,
      thumbnailHeight: 174,
    },
    {
      src: "/images/dress13.JPG",
      thumbnail: "/images/dress13.JPG",
      thumbnailWidth: 175,
      thumbnailHeight: 174,
    },
  ],
  deco: [
    {
      src: "/images/deco1.JPEG",
      thumbnail: "/images/deco1.JPEG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/deco2.jpg",
      thumbnail: "/images/deco2.jpg",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/deco3.JPG",
      thumbnail: "/images/deco3.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/deco4.JPG",
      thumbnail: "/images/deco4.JPG",
      thumbnailWidth: 250,
      thumbnailHeight: 174,
    },
    {
      src: "/images/deco5.JPG",
      thumbnail: "/images/deco5.JPG",
      thumbnailWidth: 250,
      thumbnailHeight: 174,
    },
    {
      src: "/images/deco6.JPG",
      thumbnail: "/images/deco6.JPG",
      thumbnailWidth: 175,
      thumbnailHeight: 174,
    },
    {
      src: "/images/deco7.JPG",
      thumbnail: "/images/deco7.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/deco8.jpg",
      thumbnail: "/images/deco8.jpg",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/deco9.jpg",
      thumbnail: "/images/deco9.jpg",
      thumbnailWidth: 125,
      thumbnailHeight: 174,
    },
    {
      src: "/images/deco10.jpg",
      thumbnail: "/images/deco10.jpg",
      thumbnailWidth: 125,
      thumbnailHeight: 174,
    },
    {
      src: "/images/deco11.jpg",
      thumbnail: "/images/deco11.jpg",
      thumbnailWidth: 210,
      thumbnailHeight: 174,
    },
    {
      src: "/images/deco12.jpg",
      thumbnail: "/images/deco12.jpg",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/deco13.jpg",
      thumbnail: "/images/deco13.jpg",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/deco14.jpg",
      thumbnail: "/images/deco14.jpg",
      thumbnailWidth: 130,
      thumbnailHeight: 174,
    },
    {
      src: "/images/deco15.jpg",
      thumbnail: "/images/deco15.jpg",
      thumbnailWidth: 190,
      thumbnailHeight: 174,
    },
    {
      src: "/images/deco16.jpg",
      thumbnail: "/images/deco16.jpg",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/deco17.jpg",
      thumbnail: "/images/deco17.jpg",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
  ],
  about: [
    {
      src: "/images/makeup20.jpg",
      thumbnail: "/images/makeup20.jpg",
      thumbnailWidth: 300,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup21.jpg",
      thumbnail: "/images/makeup21.jpg",
      thumbnailWidth: 140,
      thumbnailHeight: 174,
    },
    {
      src: "/images/artist2.JPG",
      thumbnail: "/images/artist2.JPG",
      thumbnailWidth: 300,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup18.JPG",
      thumbnail: "/images/makeup18.JPG",
      thumbnailWidth: 220,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup19.JPG",
      thumbnail: "/images/makeup19.JPG",
      thumbnailHeight: 174,
      thumbnailWidth: 270,
    },
    {
      src: "/images/artist1.JPG",
      thumbnail: "/images/artist1.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeupBA6.jpg",
      thumbnail: "/images/makeupBA6.jpg",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeupBA1.JPEG",
      thumbnail: "/images/makeupBA1.JPEG",
      thumbnailWidth: 300,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeupBA2.JPEG",
      thumbnail: "/images/makeupBA2.JPEG",
      thumbnailWidth: 300,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeupBA3.JPEG",
      thumbnail: "/images/makeupBA3.JPEG",
      thumbnailWidth: 300,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeupBA4.JPEG",
      thumbnail: "/images/makeupBA4.JPEG",
      thumbnailWidth: 300,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeupBA5.JPEG",
      thumbnail: "/images/makeupBA5.JPEG",
      thumbnailWidth: 300,
      thumbnailHeight: 174,
    },
    {
      src: "/images/makeup10.JPG",
      thumbnail: "/images/makeup10.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/hair1.JPG",
      thumbnail: "/images/hair1.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/hair3.JPG",
      thumbnail: "/images/hair3.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/hair4.JPG",
      thumbnail: "/images/hair4.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/hair5.JPG",
      thumbnail: "/images/hair5.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/hair6.JPG",
      thumbnail: "/images/hair6.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/hair7.JPG",
      thumbnail: "/images/hair7.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/pose1.JPG",
      thumbnail: "/images/pose1.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/pose2.JPG",
      thumbnail: "/images/pose2.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
    {
      src: "/images/pose3.JPG",
      thumbnail: "/images/pose3.JPG",
      thumbnailWidth: 150,
      thumbnailHeight: 174,
    },
  ],
};
